name: ch10_fastcampus_freezed
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.5
  freezed: ^3.0.6
  build_runner: ^2.5.3

flutter:
  uses-material-design: true
